Repository versori/versori-js-sdk, pull requests merged in 2023-11, with the labels that each got.

#6 Setup ci and release
  .github/workflows/pull-request.yml
  .github/workflows/release.yml
  .releaserc.json
  README.md
  package.json
Labels: size/L

#7 fix: remove testing changes
  .github/workflows/release.yml
Labels: size/XS

#8 fix: endpoint url. Add some basic reset css in sdk.
  src/switchboard/v1alpha1/sdk/sdk.ts
  src/switchboard/v1alpha1/styles/styles.css
Labels: size/M
